// v2/lib/prodScoring.js — mirrors the production scoring engine in app/page.js.
// Kept isolated so the v2 preview can evolve the visual design without diverging
// from the canonical surf logic. Any update to the scoring rules must land in
// both files (or be extracted to a third shared module) — for now we copy.

export const mToFt = m => m * 3.281;
export const knToKmh = kn => kn * 1.852;

export function estimateFaceHeight(swellHeight, swellPeriod) {
  const periodFactor = Math.min(1.8, Math.max(0.7, swellPeriod / 10));
  return swellHeight * periodFactor;
}

export const TIDE_TARGETS = { "low": 0.1, "mid-low": 0.3, "mid": 0.5, "mid-high": 0.7, "high": 0.9 };

export function scoreSurf(h, spot, tideCtx) {
  const { swellHeight, swellPeriod, swellDir, windSpeedKn, windDir } = h;
  let s = 0;
  const notes = [];

  if (swellPeriod >= 14) { s += 35; notes.push("n_long"); }
  else if (swellPeriod >= 11) { s += 22; notes.push("n_decent"); }
  else if (swellPeriod >= 8) { s += 10; notes.push("n_short"); }
  else notes.push("n_weak");

  if (swellHeight >= 1.8) { s += 30; notes.push("n_solid"); }
  else if (swellHeight >= 1.0) { s += 20; notes.push("n_good"); }
  else if (swellHeight >= 0.5) { s += 10; notes.push("n_small"); }
  else notes.push("n_flat");

  const swellDelta = Math.abs(((swellDir - spot.idealSwellDir + 540) % 360) - 180);
  if (swellDelta <= 30) { s += 20; notes.push("n_ideal_dir"); }
  else if (swellDelta <= 60) { s += 8; notes.push("n_ok_dir"); }
  else { s -= 5; notes.push("n_wrong_dir"); }

  if (h.secSwellH != null && h.secSwellDir != null && h.secSwellH >= 0.5 && swellDelta > 60) {
    const secDelta = Math.abs(((h.secSwellDir - spot.idealSwellDir + 540) % 360) - 180);
    if (secDelta <= 30) { s += 10; notes.push("n_sec_helps"); }
    else if (secDelta <= 60) { s += 4; notes.push("n_sec_helps"); }
  }

  const windDelta = Math.abs(((windDir - spot.offshoreWindDir + 540) % 360) - 180);
  const isOffshore = windDelta <= 45;
  const isOnshore = windDelta >= 135;
  const kmh = knToKmh(windSpeedKn);

  if (isOffshore) {
    if (kmh < 10) { s += 18; notes.push("n_light_off"); }
    else if (kmh < 25) { s += 15; notes.push("n_off"); }
    else if (kmh < 40) { s += 5; notes.push("n_strong_off"); }
    else { s -= 5; notes.push("n_gale_off"); }
  } else if (isOnshore) {
    if (kmh < 10) { s -= 2; notes.push("n_light_on"); }
    else if (kmh < 20) { s -= 10; notes.push("n_on_bumpy"); }
    else if (kmh < 35) { s -= 20; notes.push("n_on_blown"); }
    else { s -= 30; notes.push("n_heavy_on"); }
  } else {
    if (kmh < 10) { s += 5; notes.push("n_light_x"); }
    else if (kmh < 25) { s -= 3; notes.push("n_x_texture"); }
    else { s -= 12; notes.push("n_strong_x"); }
  }

  if (tideCtx && spot.idealTide && spot.idealTide !== "any" && h.tideM != null) {
    const range = tideCtx.max - tideCtx.min;
    if (range > 0.15) {
      const norm = (h.tideM - tideCtx.min) / range;
      const target = TIDE_TARGETS[spot.idealTide];
      if (target != null) {
        const delta = Math.abs(norm - target);
        if (delta < 0.15) { s += 6; notes.push("n_tide_prime"); }
        else if (delta < 0.3) { s += 2; notes.push("n_tide_ok"); }
        else if (delta > 0.6) { s -= 6; notes.push("n_tide_wrong"); }
      }
    }
  }

  // Gusts penalty — a moderate mean wind with violent gusts is significantly
  // messier than a steady mean wind of the same speed. Gust delta (gust - mean)
  // greater than 15 km/h = noticeably choppy; > 25 km/h = genuinely hard.
  if (h.windGustKn != null) {
    const gustKmh = knToKmh(h.windGustKn);
    const delta = gustKmh - kmh;
    if (delta >= 25) { s -= 8; notes.push("n_gusty_heavy"); }
    else if (delta >= 15) { s -= 4; notes.push("n_gusty"); }
  }

  // Windswell penalty — `wind_wave_height` is the chop generated by local wind.
  // When it's a significant fraction of the total swell AND the swell period is
  // short, the wave face is textured and hard to read. #1 reason a "decent
  // groundswell day" still surfs like junk.
  if (h.windWaveHeight != null && swellHeight > 0.3) {
    const ratio = h.windWaveHeight / Math.max(0.3, swellHeight);
    if (ratio >= 0.8 && swellPeriod < 11) { s -= 10; notes.push("n_messy_windswell"); }
    else if (ratio >= 0.5 && swellPeriod < 10) { s -= 5; notes.push("n_windswell"); }
  }

  return { score: Math.max(0, Math.min(100, s)), notes };
}

export function findNextTideEvent(hours, fromTime) {
  if (!hours || hours.length < 3) return null;
  const fromIdx = hours.findIndex(h => h.time === fromTime);
  const start = fromIdx >= 0 ? fromIdx : 0;
  for (let i = Math.max(1, start); i < hours.length - 1; i++) {
    const prev = hours[i - 1]?.tideM;
    const cur  = hours[i].tideM;
    const next = hours[i + 1]?.tideM;
    if (prev == null || cur == null || next == null) continue;
    if (cur > prev && cur >= next) return { kind: "high", time: hours[i].time, m: cur };
    if (cur < prev && cur <= next) return { kind: "low",  time: hours[i].time, m: cur };
  }
  return null;
}

export function dayTideCtx(dayHours) {
  if (!dayHours || !dayHours.length) return null;
  let min = Infinity, max = -Infinity, count = 0;
  for (const h of dayHours) {
    if (h.tideM == null) continue;
    if (h.tideM < min) min = h.tideM;
    if (h.tideM > max) max = h.tideM;
    count++;
  }
  if (count < 2) return null;
  return { min, max };
}

export function tideTrend(hours, sel) {
  if (!hours || !sel) return null;
  const idx = hours.findIndex(h => h.time === sel.time);
  if (idx < 1 || sel.tideM == null) return null;
  const prev = hours[idx - 1]?.tideM;
  if (prev == null) return null;
  const diff = sel.tideM - prev;
  if (Math.abs(diff) < 0.05) return "steady";
  return diff > 0 ? "rising" : "falling";
}

// v1 getWindTypeKey — returns translation key ("offshore"/"onshore"/"cross_shore")
// so the wind sub can read "S · cross-shore" in 12 languages.
export function getWindTypeKey(sel, spot) {
  const d = Math.abs(((sel.windDir - spot.offshoreWindDir + 540) % 360) - 180);
  if (d <= 45) return "offshore";
  if (d >= 135) return "onshore";
  return "cross_shore";
}

export function degToCompass(deg) {
  const dirs = ["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"];
  return dirs[Math.round(deg / 22.5) % 16];
}

export function fmtLongDay(isoDate, tz, t) {
  const [y, mo, d] = isoDate.split("-").map(Number);
  const dayDate = new Date(Date.UTC(y, mo - 1, d, 12));
  const todayStr = new Date().toLocaleDateString("en-CA", { timeZone: tz });
  const diffDays = Math.round((dayDate.getTime() - new Date(todayStr + "T12:00:00Z").getTime()) / (1000*60*60*24));
  if (diffDays === 0) return t("today");
  if (diffDays === 1) return t("tomorrow");
  if (diffDays === -1) return t("yesterday");
  return dayDate.toLocaleDateString("en-AU", { weekday: "short", day: "numeric", month: "short", timeZone: "UTC" });
}

export function offsetDate(isoDate, n) {
  const [y, mo, d] = isoDate.split("-").map(Number);
  const dt = new Date(Date.UTC(y, mo - 1, d));
  dt.setUTCDate(dt.getUTCDate() + n);
  return dt.toISOString().slice(0, 10);
}

// ── Per-user-level advice ──────────────────────────────────────────────
export const USER_LEVELS = ["first_timer", "beginner", "early_int", "intermediate", "advanced", "expert"];

export const USER_LEVEL_ZONES = {
  first_timer:  { min: 0.3, sweetLo: 0.6, sweetHi: 1.5, upperMax: 2.2 },
  beginner:     { min: 0.3, sweetLo: 1,   sweetHi: 2,   upperMax: 3 },
  early_int:    { min: 1.2, sweetLo: 1.8, sweetHi: 3,   upperMax: 4 },
  intermediate: { min: 1.5, sweetLo: 2.5, sweetHi: 4.5, upperMax: 6 },
  advanced:     { min: 2,   sweetLo: 3,   sweetHi: 7,   upperMax: 10 },
  expert:       { min: 2.5, sweetLo: 4,   sweetHi: 10,  upperMax: 16 },
};

export function classifyConditions(userLevel, h, spot) {
  const faceFt = mToFt(estimateFaceHeight(h.swellHeight, h.swellPeriod));
  const kmh = knToKmh(h.windSpeedKn);
  const windDelta = Math.abs(((h.windDir - spot.offshoreWindDir + 540) % 360) - 180);
  const isOffshore = windDelta <= 45;
  const isOnshore = windDelta >= 90;

  const z = USER_LEVEL_ZONES[userLevel] || USER_LEVEL_ZONES.intermediate;
  let size;
  if (faceFt < z.min) size = "too_small";
  else if (faceFt < z.sweetLo) size = "small";
  else if (faceFt <= z.sweetHi) size = "sweet";
  else if (faceFt <= z.upperMax) size = "upper";
  else size = "too_big";

  // Wind thresholds aligned with scoreSurf's onshore classification
  // (20 km/h = n_on_blown) so the label never contradicts the score number.
  // Only first_timer + beginner get the tighter 18 km/h threshold — they
  // haven't built the paddling / duck-diving chops yet. Early_int uses the
  // same 20 km/h as intermediate; they're between beginner and intermediate
  // in skill and the verdict ladder must stay monotonic.
  const isEarlyLearner = userLevel === "first_timer" || userLevel === "beginner";
  const blownNonOffshore = isEarlyLearner ? 18 : 20;
  const galeOffshore     = isEarlyLearner ? 45 : 55;

  let wind;
  if ((isOffshore && kmh < 25) || kmh < 8) wind = "clean";
  else if ((!isOffshore && kmh >= blownNonOffshore) || kmh >= 40 || (isOffshore && kmh >= galeOffshore)) wind = "blown";
  else wind = "bumpy";

  const reefTooMuch = (spot.heavy || spot.type === "reef") && isEarlyLearner;

  // Ocean-current hazard for early-learners — a rip drains a beginner faster
  // than they can paddle against it. Open-Meteo returns velocity in m/s;
  // 0.28 m/s ≈ 1 km/h, 0.56 m/s ≈ 2 km/h.
  const curVel = h.currentVel || 0;
  const currentHazard = isEarlyLearner && curVel >= 0.56 ? "dangerous"
                      : isEarlyLearner && curVel >= 0.28 ? "strong"
                      : "none";
  return { size, wind, reefTooMuch, faceFt, currentHazard };
}

// isFoamieFriendly — the subset of users who should literally be riding a
// foamie (soft-top) as their primary board. First-timer + beginner only.
// Used by the board recommendation logic.
export function isFoamieFriendly(userLevel, spot) {
  return (userLevel === "first_timer" || userLevel === "beginner")
    && spot.type !== "reef" && !spot.heavy;
}

// hasInsideReform — the BROADER group that can fall back to the inside
// reform (smaller re-formed waves closer to shore) when the main peak is
// too big, too messy or blown out. Includes early_int: they paddle a
// mid-length, not a foamie, but they can still bail the outside and
// surf whitewater / inside walls when conditions demand it. Beach breaks
// only — heavy or reef spots don't offer this escape.
export function hasInsideReform(userLevel, faceFt, spot) {
  const eligible = userLevel === "first_timer"
                || userLevel === "beginner"
                || userLevel === "early_int";
  return eligible && spot.type !== "reef" && !spot.heavy && faceFt <= 10;
}

// Advice key is verdict-aware: the tip must always match the SKIP / MAYBE /
// GO decision. Previously the tip path and the verdict path ran
// independently so you could get "SKIP" with a "go surf the inside" tip
// when the wind was too strong even for the inside reform. Now the
// verdict gates which branch the tip is picked from.
export function getPersonalAdviceKey(userLevel, h, spot) {
  const { size, wind, reefTooMuch, faceFt, currentHazard } = classifyConditions(userLevel, h, spot);
  const verdict = getPersonalVerdict(userLevel, h, spot);
  const foamie = hasInsideReform(userLevel, faceFt, spot);
  const { kmh } = windContext(h, spot);
  const isLearner = userLevel === "first_timer" || userLevel === "beginner" || userLevel === "early_int";

  // ── SKIP branch — explain why it's a no ─────────────────────────────
  if (verdict === "no") {
    if (currentHazard === "dangerous" && isLearner) return "tip_" + userLevel + "_current";
    if (reefTooMuch) return "tip_" + userLevel + "_reef";
    // Gale wind trumps everything else — unsurfable for any reason.
    if (kmh >= 35) return "tip_" + userLevel + "_gale";
    if (faceFt < 0.3) return "tip_" + userLevel + "_too_small";
    if (size === "too_big") return "tip_" + userLevel + "_too_big";
    if (size === "too_small") return "tip_" + userLevel + "_too_small";
    if (wind === "blown") return "tip_" + userLevel + "_blown_" + (size === "too_small" ? "small" : size === "too_big" ? "upper" : size);
    return "tip_" + userLevel + "_upper_bumpy"; // catch-all for edge cases
  }

  // ── MAYBE branch — surfable with caveats ────────────────────────────
  if (verdict === "ok") {
    // Learner rescue: outside is out of reach but the inside still offers
    // rideable reforms. Only reached when wind < 25 km/h (the learner cap
    // in getPersonalVerdict), so this tip is always truthful.
    if (foamie && (size === "too_big" || size === "upper" || wind === "blown")) {
      return "tip_" + userLevel + "_inside";
    }
    if (size === "too_big") return "tip_" + userLevel + "_too_big";
    if (size === "too_small") return "tip_" + userLevel + "_too_small";
    if (wind === "blown") return "tip_" + userLevel + "_blown_" + size;
    return "tip_" + userLevel + "_" + size + "_" + wind;
  }

  // ── GO branch — send it ─────────────────────────────────────────────
  return "tip_" + userLevel + "_" + size + "_" + wind;
}

export function getPersonalModifier(userLevel, h, spot) {
  const { size, wind, reefTooMuch } = classifyConditions(userLevel, h, spot);
  if (reefTooMuch) return null;
  if (size === "too_small" || size === "too_big") return null;
  if (wind === "blown") return null;

  const period = h.swellPeriod || 0;
  const dirDelta = Math.abs(((h.swellDir - spot.idealSwellDir + 540) % 360) - 180);
  const isLearner = userLevel === "first_timer" || userLevel === "beginner" || userLevel === "early_int";

  if (period >= 14 && (size === "sweet" || size === "upper")) return "tip_mod_long_period";
  if (period > 0 && period < 8 && isLearner && (size === "sweet" || size === "small")) return "tip_mod_short_period";
  if (dirDelta > 75) return "tip_mod_off_angle";
  if (wind === "clean" && knToKmh(h.windSpeedKn) < 8) return "tip_mod_glassy";
  return null;
}

// Board recommendation per level + face size + period. Returns a short label
// for inline display plus a longer explanation for tooltips / ScoreSheet.
// First-timer and beginner always stay on a foamie (soft-top) — it's safer
// for them and anyone around them, and takes-offs are much more forgiving.
// When size / wind exceed their level we recommend riding the INSIDE reform
// on the foamie (whitewash after the peak breaks), never the outside peak.
export function getBoardRec(userLevel, faceFt, period, spot) {
  const foamie = isFoamieFriendly(userLevel, spot);
  const longP = period >= 12;
  if (userLevel === "first_timer") {
    if (faceFt < 0.6) return { short: "—", long: "Not enough wave — save your wax" };
    if (faceFt <= 2)  return { short: "Foamie 8'+", long: "8' or bigger soft-top. Stay in the whitewash — catch re-formed waves near the sand, don't paddle past the break" };
    if (foamie && faceFt <= 10) return { short: "Foamie inside only", long: "Peak is too much for a first-timer. Stay INSIDE on a foamie and ride the reform (smaller waves that form after the main wave breaks)" };
    return { short: "Watch today", long: "Beyond a first-timer's kit. Watch the ocean, learn where the rip is, try again when it's smaller" };
  }
  if (userLevel === "beginner") {
    if (faceFt < 0.6) return { short: "—", long: "Not enough wave" };
    if (faceFt <= 3)  return { short: "Foamie 7'–8'", long: "Soft-top 7' to 8' — easy paddle, forgiving take-offs, safer for everyone if you lose it" };
    if (foamie && faceFt <= 8) return { short: "Foamie inside", long: "Peak's getting big — stay on the foamie in the reform (the smaller foam waves close to shore)" };
    return { short: "Wait smaller", long: "Too much for a beginner foamie — come back when it drops" };
  }
  if (userLevel === "early_int") {
    if (faceFt < 1.2) return { short: "Longboard 9'", long: "Only a longboard will catch this little energy" };
    if (faceFt <= 2.5) return { short: "Mid-length 7'", long: "7'0–7'6 mid-length. Plenty of paddle, catches cleanly, still forgiving on take-offs" };
    if (faceFt <= 4)  return { short: "Mid 6'10 / SB 6'8", long: "Mid-length 6'10 if you want easy waves, or try a shortboard 6'6–6'8 if you're feeling confident" };
    if (faceFt <= 6)  return { short: "Pick your waves", long: "Size is on the edge — stick with the mid-length, don't force the biggest sets, take the inside ones" };
    return { short: "Hold back", long: "Out of your range — watch a set, don't go unless you know the rip and the paddle-out" };
  }
  if (userLevel === "intermediate") {
    if (faceFt < 1.5) return { short: "Longboard", long: "Too soft for a shortboard — longboard or step off" };
    if (faceFt <= 2.5) return { short: "Fish / groveler 5'8–6'0", long: "Small-wave blade — a fish or groveler with volume so you keep moving through the soft sections" };
    if (faceFt <= 4.5) return { short: "Shortboard 5'11–6'4", long: "Your daily driver — the sweet spot for progressive surfing" };
    if (faceFt <= 6.5) return { short: longP ? "Step-up 6'4–6'6" : "Shortboard 6'2+", long: "Slightly longer board for paddle power and hold. On a long-period day size up a little" };
    return { short: "Hold back", long: "Overhead-plus is beyond your comfort zone — watch a set or two, don't force it" };
  }
  if (userLevel === "advanced") {
    if (faceFt < 2) return { short: "Longboard / fish", long: "Longboard for fun, or a fish if there's any push" };
    if (faceFt <= 3)  return { short: "Fish / groveler", long: "Small-wave board with volume" };
    if (faceFt <= 6)  return { short: "Shortboard 6'0–6'4", long: "Your daily driver zone" };
    if (faceFt <= 9)  return { short: "Step-up 6'6–7'0", long: "Step up — a bit more foam and length for paddle and hold in bigger surf" };
    if (faceFt <= 12) return { short: "Mini-gun 7'2+", long: "Big-wave territory — length and rail for commitment in the drop" };
    return { short: "Gun 7'6+", long: "Full big-wave kit — know the spot, know your limits, never alone" };
  }
  if (userLevel === "expert") {
    if (faceFt < 2)   return { short: "Longboard", long: "Fun longboard day" };
    if (faceFt <= 3)  return { short: "Groveler", long: "Small-wave blade" };
    if (faceFt <= 6)  return { short: "Shortboard", long: "Daily driver — whatever's in your bag for this size" };
    if (faceFt <= 9)  return { short: "Step-up 6'6–7'0", long: "Step up for paddle and hold" };
    if (faceFt <= 12) return { short: "Gun 7'2–7'6", long: "Proper gun — drop-ins and hold" };
    return { short: "Big-wave gun 8'+", long: "Full big-wave kit — tow options, safety crew, full protocol" };
  }
  return null;
}

// Strategy / safety bullets — contextual advice based on level + hour +
// day-wide patterns. Returns an array of short imperative strings that the
// UI can render as bullet points. Covers: current/rip safety, crowd, wind
// shift timing, tide strategy, period warnings.
export function getSessionNotes(userLevel, h, dayHours, spot) {
  const out = [];
  if (!h || !spot) return out;
  const cls = classifyConditions(userLevel, h, spot);
  const { size, wind, currentHazard } = cls;
  const kmh = knToKmh(h.windSpeedKn);

  // Safety first — current / rip
  if (currentHazard === "dangerous") {
    out.push("⚠ Strong rip running — do not paddle out, check with a lifeguard first");
  } else if (currentHazard === "strong") {
    out.push("⚠ Noticeable current — surf between flags, don't drift past the break");
  }

  // Reef / heavy spot warnings for levels below advanced
  if ((spot.heavy || spot.type === "reef") && (userLevel === "early_int" || userLevel === "intermediate")) {
    out.push("Reef / heavy spot — know the entry, watch the locals, don't drop in");
  }

  // Foamie inside advice for learners when conditions are too much
  if (isFoamieFriendly(userLevel, spot) && (size === "too_big" || size === "upper" || wind === "blown") && cls.faceFt <= 10 && cls.faceFt >= 0.3) {
    out.push("Stay INSIDE on the foamie — ride the reform close to shore, smaller and forgiving");
  }

  // Wind shift forecast — clean now but blows up later
  if (dayHours && wind !== "blown") {
    const myIdx = dayHours.findIndex((x) => x.time === h.time);
    if (myIdx >= 0) {
      const later = dayHours.slice(myIdx + 1).find((hh) => knToKmh(hh.windSpeedKn) > 22);
      if (later) {
        const laterH = new Date(later.time).getHours();
        out.push(`Wind picks up around ${laterH}:00 — prioritize the early`);
      }
    }
  }

  // Period warnings
  const period = h.swellPeriod || 0;
  if (period >= 13 && (userLevel === "first_timer" || userLevel === "beginner" || userLevel === "early_int")) {
    out.push("Long-period swell — waves hit harder than they look, be patient with take-offs");
  } else if (period > 0 && period < 8 && (size === "sweet" || size === "upper")) {
    out.push("Short period — waves close out faster, read the line quickly or miss the wall");
  }

  // Cross-shore warning at bigger sizes for mid levels
  if (wind === "bumpy" && kmh >= 18 && (userLevel === "intermediate" || userLevel === "early_int")) {
    out.push("Cross-shore texture — paddle wider for a clean face, avoid the chop zones");
  }

  return out;
}

export function getTideModifier(sel, hours) {
  if (!sel || sel.tideM == null || !hours) return null;
  const trend = tideTrend(hours, sel);
  const next = findNextTideEvent(hours, sel.time);
  if (!next) return null;
  const hoursUntil = (new Date(next.time) - new Date(sel.time)) / 3600000;
  if (hoursUntil >= 0 && hoursUntil <= 2) {
    return next.kind === "high" ? "tip_mod_tide_high_soon" : "tip_mod_tide_low_soon";
  }
  if (trend === "rising") return "tip_mod_tide_rising";
  if (trend === "falling") return "tip_mod_tide_falling";
  return null;
}

// Wind "flavor" relative to the spot: direction class + kmh in one call.
// Keeps the universal-gale logic below from repeating itself.
function windContext(h, spot) {
  const kmh = knToKmh(h.windSpeedKn);
  const delta = Math.abs(((h.windDir - spot.offshoreWindDir + 540) % 360) - 180);
  const dir = delta <= 45 ? "offshore" : delta >= 135 ? "onshore" : "cross";
  return { kmh, dir };
}

// Universal gale cap — a full-on windy day kills a session at any skill
// level at a beach break. Onshore is the strictest (sets get shredded
// before they form), cross-shore next (sideways chop), offshore the most
// permissive (experts can still score if the swell is there, but they
// get picked off their boards).
function galeKills(userLevel, kmh, dir) {
  const isPro = userLevel === "advanced" || userLevel === "expert";
  if (dir === "onshore" && kmh >= 35) return true;
  if (dir === "cross"   && kmh >= 40 && !isPro) return true;
  if (dir === "cross"   && kmh >= 50) return true;
  if (dir === "offshore" && kmh >= 50 && !isPro) return true;
  if (dir === "offshore" && kmh >= 65) return true;
  return false;
}

export function getPersonalVerdict(userLevel, h, spot) {
  const { size, wind, reefTooMuch, faceFt, currentHazard } = classifyConditions(userLevel, h, spot);
  // Current safety — overrides everything for learners who can't paddle
  // against a rip. "dangerous" = hard no; "strong" caps the verdict to
  // MAYBE below (never lets a learner see GO on a rippy day).
  if (currentHazard === "dangerous") return "no";
  if (reefTooMuch) return "no";

  const { kmh, dir } = windContext(h, spot);
  // Universal gale cap — applies to all levels. Even advanced/expert
  // don't get a rideable session at a beach break in a gale onshore.
  if (galeKills(userLevel, kmh, dir)) return "no";

  if (hasInsideReform(userLevel, faceFt, spot)) {
    if (faceFt < 0.3) return "no";
    // Learner-specific inside-reform cap: 25 km/h any direction. The
    // foamie/mid-length group can't handle more than that — 25+ onshore
    // is shorebreak chop, 25+ cross is side-chop, 25+ offshore picks them
    // off their boards. The universal cap above already handles the
    // harder gale range; this is the tighter learner-only threshold.
    if (kmh >= 25) return "no";
    if (size === "sweet" && wind === "clean") return "yes";
    return "ok";
  }
  if (wind === "blown") {
    if (size === "upper") return "no";
    if (size === "too_small") return "no";
    // Safety-first: blown wind + foamie-eligible learner (first_timer /
    // beginner) = HARD no. They can't punch through chop yet — the inside
    // reform rescue above already covers their fall-back. Early_int drops
    // through to "ok" like intermediate, since they're on a mid-length or
    // shortboard and can handle moderate blown conditions at the right size.
    if (userLevel === "first_timer" || userLevel === "beginner") return "no";
    return "ok";
  }
  if (size === "too_small") {
    if (userLevel === "first_timer" || userLevel === "beginner") return "no";
    return "ok";
  }
  if (size === "too_big") {
    // Foamie-eligible learners (first_timer / beginner) get the inside-
    // reform rescue above and never fall through to here. Early_int is
    // NOT on a foamie but they have enough paddle/duck-dive skill to
    // attempt — "ok" (MAYBE) instead of hard-no keeps the level ladder
    // monotonic (never stricter than beginner).
    if (userLevel === "first_timer" || userLevel === "beginner") return "no";
    return "ok";
  }
  const cap = currentHazard === "strong" ? "ok" : null;
  const downgrade = (v) => (cap && v === "yes" ? cap : v);
  if (size === "sweet") return downgrade(wind === "clean" ? "yes" : "ok");
  if (size === "upper") return downgrade(wind === "clean" ? "yes" : "ok");
  return "ok";
}

// Per-level score — adjusts the baseline scoreSurf value so a single /100
// reflects how good the session would be FOR THIS USER. A 2m offshore day
// is pumping for an intermediate but too-big for a first-timer — baseline
// would give them both ~85; this shifts the first-timer's view down to ~35.
// The LevelMatrix row at the bottom of the app still shows the absolute
// per-level verdict (GO/MAYBE/SKIP) unchanged, so users can see where their
// day sits relative to others.
export function scoreForLevel(h, spot, userLevel, tideCtx) {
  const base = scoreSurf(h, spot, tideCtx);
  if (!userLevel) return base;
  const { size, wind, reefTooMuch, currentHazard } = classifyConditions(userLevel, h, spot);
  const verdict = getPersonalVerdict(userLevel, h, spot);

  let adj = base.score;

  // Size zone relative to the user's level.
  if (size === "too_small") adj -= 22;
  else if (size === "small") adj -= 8;
  else if (size === "sweet") adj += 10;
  else if (size === "upper") adj -= 6;
  else if (size === "too_big") adj -= 40;

  // Wind quality on top of size. "blown" stacks hard for learners because
  // classifyConditions already uses a lower threshold (18 km/h non-offshore).
  if (wind === "blown") {
    const isLearner = userLevel === "first_timer" || userLevel === "beginner" || userLevel === "early_int";
    adj -= isLearner ? 30 : 18;
  } else if (wind === "bumpy") {
    adj -= 5;
  } else if (wind === "clean") {
    adj += 4;
  }

  if (reefTooMuch) adj -= 30;
  if (currentHazard === "dangerous") adj -= 50;
  else if (currentHazard === "strong") adj -= 15;

  // Verdict-aware ceiling — the numeric score must agree with the verdict
  // label the user sees. A SKIP can never read > 40; a MAYBE can never read
  // > 70. Without this, score+verdict contradict each other (e.g. 74/100
  // with a red SKIP label — bad UX, user already flagged this in prod).
  if (verdict === "no") adj = Math.min(adj, 38);
  else if (verdict === "ok") adj = Math.min(adj, 70);

  return { score: Math.max(0, Math.min(100, Math.round(adj))), notes: base.notes };
}

// Rebuilds a forecast payload so every hour.score is the level-adjusted
// value, and each day.bestHour is recomputed from that adjusted set. Safe
// to call on every userLevel change — O(days × hours), hundreds of ops.
// Returns a shallow-cloned payload so React sees new refs.
export function adaptForecastToLevel(payload, userLevel, spot) {
  if (!payload || !payload.days) return payload;
  if (!userLevel) return payload;
  const days = payload.days.map((d) => {
    const tideCtx = d.tideCtx || dayTideCtx(d.hours);
    const hours = d.hours.map((h) => {
      const hDeg = { ...h, swellDir: h.swellDirDeg ?? h.swellDir, windDir: h.windDirDeg ?? h.windDir };
      const { score } = scoreForLevel(hDeg, spot, userLevel, tideCtx);
      return { ...h, baseScore: h.baseScore ?? h.score, score };
    });
    let best = hours[0];
    for (const hh of hours) if (hh.score > best.score) best = hh;
    const bestLevel = getLevel(best.score, best, spot);
    return { ...d, hours, bestHour: best, bestLevel };
  });
  return { ...payload, days };
}

export function inferSpotProfile(allHours) {
  if (!allHours || allHours.length < 5) return null;
  const dirs = allHours.map(h => h.swellDir).filter(d => d != null && d >= 0);
  if (dirs.length < 5) return null;
  let sumX = 0, sumY = 0;
  for (const d of dirs) {
    sumX += Math.cos(d * Math.PI / 180);
    sumY += Math.sin(d * Math.PI / 180);
  }
  const avg = (Math.atan2(sumY, sumX) * 180 / Math.PI + 360) % 360;
  return { idealSwellDir: avg, offshoreWindDir: (avg + 180) % 360 };
}

export function distanceKm(lat1, lng1, lat2, lng2) {
  const R = 6371;
  const toRad = d => d * Math.PI / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}
